name: Login to Azure
description: >
  Logs in to Azure using OpenID Connect by impersonating a Service Principal or Managed Credential. After a successful
  login, the action will set up the necessary credentials and environment variables for the service to be able to access
  Azure resources. The service can then use these credentials to make API calls to Azure services. Intentionally not
  documented in Actions.md since it's only meant for internal use.

inputs:
  enable-az-ps-session:
    required: false
    default: 'true'
    description: Whether to enable an Az PowerShell session.

runs:
  using: composite
  steps:
    - name: Login to Azure
      uses: azure/login@a65d910e8af852a8061c627c456678983e180302 # renovate: tag=v2.2.0
      with:
        client-id: ${{ env.AZURE_CLIENT_ID }}
        tenant-id: ${{ env.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: ${{ inputs.enable-az-ps-session }}
