name: Renovate
description: >
  Runs the Renovate GitHub Action to update dependencies in the repository. Intentionally not documented in Actions.md
  since it's only meant for internal use.

inputs:
  log-level:
    type: string
    default: info
    description: The log level for Renovate (e.g., debug, info, warn, error).
  reviewers:
    type: string
    description: A comma-separated list of GitHub usernames to set as reviewers for Renovate PRs.

runs:
  using: composite
  steps:
    - name: Setup Scripts
      shell: pwsh
      run: |
        (Resolve-Path '${{ github.action_path }}/../../../Scripts').Path >> $Env:GITHUB_PATH

    - name: Prepare Reviewers
      id: reviewers
      if: ${{ inputs.reviewers != '' }}
      shell: pwsh
      run: |
        if (${{ inputs.reviewers }} -contains ',')
        {
            $array = '${{ inputs.reviewers }}' -split ',' | ForEach-Object { $PSItem.Trim() } | ConvertTo-Json -Compress
        }
        else
        {
            $array = '[${{ inputs.reviewers }}]'
        }

        Set-GitHubOutput 'array' $array
        Write-Output "reviewers: $array"

    - name: Run Renovate
      uses: renovatebot/github-action@2be773c4be8361d8182cc1b750e75bbc75af71b0 # v41.0.7
      env:
        RENOVATE_REPOSITORIES: ${{ github.repository }}
        LOG_LEVEL: ${{ inputs.log-level }}
        RENOVATE_REVIEWERS: ${{ steps.reviewers.outputs.array }}
        # Do the dependency updates when the workflow runs, not when the Renovate config tells it.
        RENOVATE_FORCE: '{''schedule'':null,''prHourlyLimit'':0}'
      with:
        token: ${{ env.CHECKOUT_TOKEN }}
