name: Codespell
# This is the same workflow you'd find in our other submodules. Unlike the rest of the workflows in this repo, this one
# is meant to actually run here, so don't call it from other repos.

on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  codespell:
    name: Codespell
    uses: Lombiq/GitHub-Actions/.github/workflows/codespell.yml@issue/OSOE-999
