name: Renovate

on:
  workflow_call:
    secrets:
      CHECKOUT_TOKEN:
        required: false
        description: >
          The GitHub token to authenticate checkout with. Pass in a GitHub personal access token if authenticated
          submodules are used. The token should be set up to also enable Renovate to work, see:
          https://github.com/renovatebot/github-action?tab=readme-ov-file#token.
    inputs:
      machine-type:
        type: string
        default: ubuntu-24.04
        description: The name of the type of machine to run the workflow under.
      log-level:
        type: string
        default: info
        description: The log level for Renovate (e.g., debug, info, warn, error).
      additional-reviewers:
        type: string
        description: A comma-separated list of GitHub usernames to add as reviewers for Renovate PRs.

jobs:
  renovate:
    runs-on: ${{ inputs.machine-type }}
    steps:
      - name: Checkout
        uses: Lombiq/GitHub-Actions/.github/actions/checkout@issue/OSOE-815-combined
        with:
          token: ${{ secrets.CHECKOUT_TOKEN }}

      - name: Run Renovate
        uses: Lombiq/GitHub-Actions/.github/actions/renovate@issue/OSOE-815-combined
        env:
          CHECKOUT_TOKEN: ${{ secrets.CHECKOUT_TOKEN }}
        with:
          log-level: ${{ inputs.log-level }}
