name: Renovate

on:
  workflow_call:
    secrets:
        CHECKOUT_TOKEN:
          required: false
          description: >
            The GitHub token to authenticate checkout with. Pass in a GitHub personal access token if authenticated
            submodules are used. The token should be set up to also enable Renovate to work, see:
            https://github.com/renovatebot/github-action?tab=readme-ov-file#token.
    inputs:
        machine-type:
          type: string
          default: ubuntu-24.04
          description: The name of the type of machine to run the workflow under.
        log-level:
          type: string
          default: info
          description: The log level for Renovate (e.g., debug, info, warn, error).

jobs:
  renovate:
    runs-on: ${{ inputs.machine-type }}
    steps:
      - name: Checkout
        uses: Lombiq/GitHub-Actions/.github/actions/checkout@dev
        with:
          token: ${{ secrets.CHECKOUT_TOKEN }}

      - name: Run Renovate
        uses: renovatebot/github-action@2be773c4be8361d8182cc1b750e75bbc75af71b0 # v41.0.7
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          LOG_LEVEL: ${{ inputs.log-level }}
          # Do the dependency updates when the workflow runs, not when the Renovate config tells it.
          RENOVATE_FORCE: '{''schedule'':null,''prHourlyLimit'':0}'
        with:
          token: ${{ secrets.CHECKOUT_TOKEN }}
